name: Pull request to main

on:
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: amqp
          tools: composer:v2, symfony

      - name: Install dependencies
        run: composer install --dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests with coverage
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text=coverage.txt --testsuite unit

      - name: Check coverage threshold
        run: |
          COVERAGE=$(grep -oP 'Lines:\s+\K\d+\.\d+' coverage.txt | head -n 1)
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 95" | bc -l) )); then
            echo "Coverage is below 95%. Failing the job."
            exit 1
          fi
