name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: amqp
          tools: composer:v2, symfony

      - name: Install dependencies
        run: composer install --dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml --testsuite unit


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
